CREATE SEQUENCE SEQ_ADMIN;
CREATE TABLE TBL_ADMIN(
    ID NUMBER CONSTRAINT PK_ADMIN PRIMARY KEY,
    ADMIN_ID VARCHAR2(1000) NOT NULL,
    ADMIN_PASSWORD VARCHAR2(1000) NOT NULL
);
SELECT * FROM TBL_ADMIN;
SELECT * FROM TBL_PAYMENT;

SELECT PAYMENT_STATUS_LOCALE, PAYMENT_POINT, CREATED_DATE, UPDATED_DATE, MEMBER_ID
FROM TBL_PAYMENT P
WHERE P.MEMBER_ID = 41