CREATE TABLE TBL_FILE(
    ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
    FILE_NAME VARCHAR2(1000) NOT NULL,
    FILE_SIZE VARCHAR2(1000) NOT NULL,
    FILE_PATH VARCHAR2(1000) NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE TBL_COMPANY_FILE(
    ID NUMBER CONSTRAINT PK_COMPANY_FILE PRIMARY KEY,
    COMPANY_ID NUMBER NOT NULL,
    COMPANY_FILE_TYPE NUMBER NOT NULL,
    CONSTRAINT FK_COMPANY_FILE_COMPANY FOREIGN KEY(COMPANY_ID)
    REFERENCES TBL_COMPANY(ID),
    CONSTRAINT FK_COMPANY_FILE_FILE FOREIGN KEY(ID)
    REFERENCES TBL_FILE(ID)
);


 CREATE SEQUENCE SEQ_FILE;
CREATE TABLE TBL_MEMBER_FILE(
    ID NUMBER CONSTRAINT PK_MEMBER_FILE PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL,
    MEMBER_FILE_TYPE VARCHAR2(1000),
    CONSTRAINT FK_MEMBER_FILE_COMPANY FOREIGN KEY(MEMBER_ID)
        REFERENCES TBL_MEMBER(ID),
    CONSTRAINT FK_MEMBER_FILE_FILE FOREIGN KEY(ID)
        REFERENCES TBL_FILE(ID)
);



/*TBL_FILE
ID
FILE_NAME
FILE_PATH
UPDATED_DATE
CREATED_DATE
//
//
TBL_COMPANY_FILE
ID
COMPANY_ID
TYPE

TBL_MEMBER_FILE
MEMBER_ID
TYPE*/

