CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER
(
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_NAME          VARCHAR2(1000) NOT NULL,
    MEMBER_PHONE         VARCHAR2(1000),
    MEMBER_EMAIL         VARCHAR2(1000) NOT NULL,
    MEMBER_PASSWORD      VARCHAR2(1000),
    MEMBER_RECENT_LOGIN  DATE           DEFAULT SYSDATE,
    MEMBER_PROFILE_PATH  VARCHAR2(1000) DEFAULT '',
    MEMBER_CLASS         VARCHAR2(1000) DEFAULT '일반',
    MEMBER_POINT         NUMBER(10)     DEFAULT 0,
    MEMBER_STATUS        VARCHAR(1000)  DEFAULT '활성',
    CREATED_DATE         DATE           DEFAULT SYSDATE,
    UPDATED_DATE         DATE           DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;
ALTER TABLE TBL_MEMBER MODIFY MEMBER_PHONE VARCHAR2(1000) NULL;
SELECT * FROM TBL_RESUME;

CREATE SEQUENCE SEQ_ADMIN;
ALTER TABLE TBL_SCRAP
    ADD CONSTRAINT FK_SCRAP_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TBL_MEMBER(id) ON DELETE CASCADE;
INSERT INTO TBL_SCRAP (ID, MEMBER_ID, PROGRAM_ID) VALUES (SEQ_SCRAP.NEXTVAL,24 , 29);
SELECT * FROM TBL_SCRAP;
DELETE FROM TBL_MEMBER WHERE ID = 2;
ALTER TABLE TBL_RESUME
    ADD CONSTRAINT FK_RESUME_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TBL_MEMBER(id) ON DELETE CASCADE;
ALTER TABLE TBL_MEMBER_INQUIRY
    ADD CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TBL_MEMBER(id) ON DELETE CASCADE;


SELECT CP.PROGRAM_NAME, CP.PROGRAM_END_DATE, CP.PROGRAM_THUMBNAIL_PATH, CP.COMPANY_NAME
FROM TBL_SCRAP S
    JOIN
    (
        SELECT COMPANY_NAME, PROGRAM_THUMBNAIL_PATH, PROGRAM_END_DATE, PROGRAM_NAME, P.ID
         FROM TBL_COMPANY C
        JOIN TBL_PROGRAM P
         ON C.ID = P.COMPANY_ID
    ) CP
ON S.PROGRAM_ID = CP.ID AND MEMBER_ID = ${id};

SELECT * FROM TBL_PROGRAM;
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_APPLY;
SELECT * FROM TBL_RESUME;


SELECT COMPANY_NAME
FROM TBL_COMPANY C JOIN TBL_PROGRAM P
ON C.ID = P.COMPANY_ID