CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER
(
    ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_NAME          VARCHAR2(1000) NOT NULL,
    MEMBER_PHONE         VARCHAR2(1000),
    MEMBER_EMAIL         VARCHAR2(1000) NOT NULL,
    MEMBER_PASSWORD      VARCHAR2(1000),
    MEMBER_RECENT_LOGIN  DATE           DEFAULT SYSDATE,
    MEMBER_PROFILE_PATH  VARCHAR2(1000) DEFAULT '',
    MEMBER_CLASS         VARCHAR2(1000) DEFAULT '일반',
    MEMBER_POINT         NUMBER(10)     DEFAULT 0,
    MEMBER_STATUS        VARCHAR(1000)  DEFAULT '활성',
    CREATED_DATE         DATE           DEFAULT SYSDATE,
    UPDATED_DATE         DATE           DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;
ALTER TABLE TBL_MEMBER MODIFY MEMBER_PHONE VARCHAR2(1000) NULL;




