CREATE SEQUENCE SEQ_REPORT;
CREATE TABLE TBL_REPORT(
                           ID NUMBER CONSTRAINT PK_REPORT PRIMARY KEY,
                           REPORT_SUBJECT VARCHAR2(1000) NOT NULL,
                           REPORT_TYPE VARCHAR2(1000) NOT NULL,
                           REPORT_DETAIL VARCHAR2(1000),
                           REPORT_STATUS VARCHAR2(1000) DEFAULT '처리중',
                           MEMBER_ID NUMBER NOT NULL,
                           CREATED_DATE DATE DEFAULT SYSDATE,
                           UPDATED_DATE DATE DEFAULT SYSDATE,
                           CONSTRAINT FK_REPORT_MEMBER FOREIGN KEY(MEMBER_ID)
                               REFERENCES TBL_MEMBER(ID)
);

SELECT * FROM TBL_REPORT
ORDER BY ID DESC;


INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '부적절한 내용', '템프 공고에 적절하지 않은 텍스트가 포함되어 있습니다.', '처리중', 2);
INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '허위정보', '신고내용2', '처리중', 2);
INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '스팸 / 도배', '신고내용3', '보류', 3);
INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '권리침해', '신고내용4', '허위신고', 12);
INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '부적절한 내용', '신고내용5', '처리완료', 13);
INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '허위정보', '신고내용6', '처리중', 2);
INSERT INTO TBL_REPORT
(ID, REPORT_SUBJECT, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES(SEQ_REPORT.NEXTVAL, '템프', '스팸 / 도배', '신고내용7', '보류', 3);